### ISSUE TITLE
first launch onAarch after clone from AUR and makepkg -si

### ISSUE THREAD

**Issue by stdcerr** [cdown/tzupdate#33]
Hi,

Just cloned tzupdate from https://aur.archlinux.org/tzupdate.git and executed makepkg -si which seemingly completed with no errors. I then got the following:
$ tzupdate  -p
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/tzupdate.py", line 64, in get_timezone
    timezone = q.get(block=True, timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 108, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tzupdate", line 11, in <module>
    load_entry_point('tzupdate==1.5.0', 'console_scripts', 'tzupdate')()
  File "/usr/lib/python3.8/site-packages/tzupdate.py", line 279, in main
    timezone = get_timezone(args.ip, timeout=args.timeout, services=services)
  File "/usr/lib/python3.8/site-packages/tzupdate.py", line 66, in get_timezone
    raise TimezoneAcquisitionError(
tzupdate.TimezoneAcquisitionError: No usable response from any API in 5.0 seconds

**Comment by cdown** [comment]
Hi! This likely means either your provider is blocking connections to the timezone lookup services, or your internet is slow or not functional. This was discussed in #32 and the default timeout was increased but, in an oversight, no new version of tzupdate was released.

For now you can use `--timeout 30` and I'll release a new version with that as the default soon.

For now you can use `--timeout 30`

**Comment by cdown** [comment]
2.0.0 released.
