### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by MoffKalast** [cdown/tzupdate#37]
When I try to run any of the specified commands I get the following:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/tzupdate", line 5, in <module>
    from tzupdate import main
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tzupdate.py", line 69
    ) from None
         ^
SyntaxError: invalid syntax

```

Installed using Pip 20 on Python 2.7 for Ubuntu 16.04

**Comment by MoffKalast** [comment]
Nevermind, works when installed using pip3.

**Comment by cdown** [comment]
Next time, you'll save yourself a lot of time by reading the trove classifiers.
